DROP TABLE IF EXISTS TB_HEROIS; /* VAI APAGAR SE EXISTIR DEPOIS CRIAR COM CREATE */
CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

/* INSERCAO DE DADOS CREATE*/
INSERT INTO TB_HEROIS (NOME, PODER)
VALUES
    ('Flash', 'Velocidade'),
    ('Aquaman', 'Falar com os animais'),
    ('Batman', 'Dinheiro')

--listar read
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME= 'Flash';

--update
UPDATE TB_HEROIS
SET NOME= 'Goku', PODER= 'Deus'
WHERE ID = 1;

--delete
DELETE FROM TB_HEROIS WHERE ID = 2;
